### ISSUE TITLE
Infinite buffering causes delays - URGENT

### ISSUE THREAD

**Issue by braraki** [roscloud/roscloud_server#12]
I am running two clients, one on a Jetson TX1 and one on my computer, which runs Ubuntu 16.04. I am also running the server on my computer. My computer is quite fast and has a lot of memory.

I'm publishing

- sensor_msgs/Imu (~ 40 Hz)
- nav_msgs/Odometry (~ 20 Hz)
- multi_car_msgs/UWBRange (0 Hz)
- vesc_msgs/VescStateStamped (~ 30 Hz)
- std_msgs/Float64 (~48 Hz)
- geometry_msgs/PoseStamped (~ 30 Hz)
- nav_msgs/OccupancyGrid (~ 0 Hz)
- tf2_msgs/TFMessage (~ 31 Hz)
- tf2_msgs/TFMessage (~ 0 Hz)

and what seems to be happening is that canopy cannot keep up with publishing all of these messages, so it accumulates them in a buffer and publishes them at a slower rate. So the messages that I see on my computer are much older than what's actually going on on the car (~ 5-10 seconds delayed in my tests).

When I share only, for example, the PoseStamped message via canopy, even though canopy publishes it at a slower rate than it receives it, I do not notice any delay in my messages.

**Comment by braraki** [comment]
just for reference, here's the bandwidth for each topic:

- imu: 16 KB/s
- odom: 36 KB/s
- vesc/sensors/core: 5.8 KB/s
- vesc/sensors/servo_position_command: 0.6 KB/s
- /slam_out_pose: 3 KB/s
- /map: 2.3 MB/s
- /tf_throttle (50 Hz): 9.8 KB/s
- /tf_static: 0.06 KB/s

**Comment by a20r** [comment]
@raphaelchang, I think this is an issue with the IOLoop not being able to deal with the volume of messages on the receiver's end. When we kill the server, delayed messages continue to publish even though all the queues in ROS are set to size 1. This means that messages are being queued in canopy_client. Is there an easy way to change from the IOLoop to a first-come-first-serve basis. This needs to be fixed by tomorrow at 15:00.

**Comment by raphaelchang** [comment]
There doesn't seem to be a simple way to make Tornado Websockets non-queueing. Also, some packets cannot be dropped because they are acknowledge packets. A solution to this could be having a message object in memory, with another thread continuously processing the current message object and the on_message callback overwriting the message object every time a new message arrives. Not sure if I could implement and test this in a day though.

**Comment by braraki** [comment]
do you think it would work if I made a new message type that combines all of the individual messages and just publish one big message at around 100hz?

**Comment by raphaelchang** [comment]
I would expect it to improve, as it would overcome the callback overhead. There is a current packet size limit of 10 MB (but should be changeable).

**Comment by raphaelchang** [comment]
This could also be a cause: http://www.tornadoweb.org/en/stable/websocket.html#tornado.websocket.WebSocketHandler.set_nodelay.

**Comment by braraki** [comment]
if you push this change I can try it now

**Comment by raphaelchang** [comment]
Never mind, I don't think that's applicable to the websocket client.
